package:
    name: mingwpy
    version: 0.1.0

source:                                                                                                # [win]
    url: https://anaconda.org/carlkl/mingwpy/0.1.0b3/download/mingwpy-0.1.0b3-cp34-none-win32.whl      # [py34 and win32]
    fn: mingwpy-0.1.0b3-cp34-none-win32.whl                                                            # [py34 and win32]
    sha256: f6b1236a6cb3dc15775c178844e18d2d8a43e2d7a1a4c7cefc683ff507967272                           # [py34 and win32]

    url: https://anaconda.org/carlkl/mingwpy/0.1.0b3/download/mingwpy-0.1.0b3-cp34-none-win_amd64.whl  # [py34 and win64]
    fn: mingwpy-0.1.0b3-cp34-none-win_amd64.whl                                                        # [py34 and win64]
    sha256: 3f7df6a464030b1468e52c7a7d8445bf9481185c33a7b5977c6d5a8227e847c4                           # [py34 and win64]

    url: https://anaconda.org/carlkl/mingwpy/0.1.0b3/download/mingwpy-0.1.0b3-cp27-none-win32.whl      # [py27 and win32]
    fn: mingwpy-0.1.0b3-cp27-none-win32.whl                                                            # [py27 and win32]
    sha256: 9d465d8f027e285dff38f017dc7ac107064273cb91b1cd70b1e62580bdfea752                           # [py27 and win32]

    url: https://anaconda.org/carlkl/mingwpy/0.1.0b3/download/mingwpy-0.1.0b3-cp27-none-win_amd64.whl  # [py27 and win64]
    fn: mingwpy-0.1.0b3-cp27-none-win_amd64.whl                                                        # [py27 and win64]
    sha256: f362fc34c10ff5d59196f04ede66454b394917fccc3420597abe25ec5ace68a6                           # [py27 and win64]

build:
    number: 2
    skip: True  # [not win or py35]

requirements:
    build:
        - python
        - setuptools
        - pip
    run:
        - python

test:
    commands:
        - gfortran.exe --version

about:
    home: https://github.com/mingwpy/mingw-builds
    license: BSD 3-clause
    summary: GCC for Windows 64 & 32 bits

extra:
    recipe-maintainers:
        - ocefpaf
