
# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27  
    - CONDA_PY=34  
    - CONDA_PY=35  
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in forge.yml.
    - secure: "nYRZQRfSBwECzMS68W5yTIkjsRhxIpacvQporVrfZPjAYZSSbHPwbeHCCb65V7R2X4XnN/nWZgzBUuJX2LpmOahYy5+1rgyPd262o6g2jvt8twsle/+ex+DDqCKYEzT01jndOU+lKhhnQsdtiEOMAY2eCZUk/xKo3w7V7Ntyk7WLWg+O/0ob0dkesKWGmnPEtO7XIud5Z6V8VNwGHEdy+1KF/2Pqd6Gr5cEi6O/fr+EEtq8BKy60qCFAlYPP9e2WRlqZPiU1Tsln3vtAGaiSjOFJEnNqhZfReaNTiUjwXdMJFA93sWaRmNYB6+ceGf+ZrePOiahJJqedY5XTI01wYVGBlitWDkGLFtW5qlEjafFTPs0KHM5qoC+Yth+33P5vmVxA0zGdc7NRxwXl7G3h/z62HpHRVSPKlAiKQKrgjmqaNzKSiPKt/UOHK90hzDVVnQpdXYCy0kxp2vCIM1kL/6DaJ6+Xeha4JMUrNVCEYnEANA/kggStVRpoGriEz4HHOB/ll1hUKsVgnLXtUsUsJK2LBZu0EeLSoeQDEsz8BrIhrmLuIQG/X4pXeHGraFVn2ivRM7UrSCwQml1v5WjcP1EszP7yJJ3kV5PgqOwxDUsGJ3y4Mt1lLNYZZm+5fu9gHCOBw4/C1WsB+mUWvQ3uj4dmVmqwHSy62/U5UhFdYe4="


install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-3.7.3-MacOSX-x86_64.sh"
      wget "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda update --yes conda
      conda install --yes conda-build jinja2 anaconda-client

      
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
